services:
    # Main serializer class
    noxlogic_serializer:
        class: Noxlogic\SerializerBundle\Service\Serializer
        arguments: [ "@doctrine", "@router", "@service_container" ]

    # Available adapters
    noxlogic_serializer.output.adapter.json:
        class: Noxlogic\SerializerBundle\Service\OutputAdapter\JsonHal
        tags:
            - { name: noxlogic.serializer.output.adapter }

    noxlogic_serializer.output.adapter.html:
        class: Noxlogic\SerializerBundle\Service\OutputAdapter\Html
        tags:
            - { name: noxlogic.serializer.output.adapter }

    noxlogic_serializer.output.adapter.xml:
        class: Noxlogic\SerializerBundle\Service\OutputAdapter\Xml
        tags:
            - { name: noxlogic.serializer.output.adapter }
