inherit: true

checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage: true
    sensiolabs_security_checker:
        enabled: true

filter:
    excluded_paths:
        - 'vendor/*'
        - 'Tests/*'
